<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Membuat beberapa data dummy user
        $users = [
            [
                'nama' => 'Admin DP3AP2KB Kota Cimahi',
                'role' => 'admin-kota',
                'username' => 'admindp3ap2kb',
                'password' => Hash::make('dp3ap2kbkotacimahi'),
                'kecamatan' => 'Cimahi Utara',
                'kelurahan' => 'Pasirkaliki',
                'rw' => '003',
                'rt' => '003',
            ],
            [
                'nama' => 'user 1',
                'role' => 'admin-kader',
                'username' => 'kader01',
                'password' => '$2y$10$6V03qG5myxsEzgnKyXoYzeyRyW11yee2X5xzRMwmA8Tem3mCp4LKS',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 2',
                'role' => 'admin-kader',
                'username' => 'kader02',
                'password' => '$2y$10$xOmWzwa88jFpaoFhf90RR.hIcGiRFS8MfUiSPq3dcKlmIV/TFwfYq',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 3',
                'role' => 'admin-kader',
                'username' => 'kader03',
                'password' => '$2y$10$heeCWaYP3glcFP/PdaxUk.lcUhzTe.7F3CdNsMrPFg2mcafTTH7uS',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 4',
                'role' => 'admin-kader',
                'username' => 'kader04',
                'password' => '$2y$10$a1P/CRpISvaEY8N9qUPMZuxJ/YeZhXIN50tOP2QVwxnQJfGlqrBpC',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 5',
                'role' => 'admin-kader',
                'username' => 'kader05',
                'password' => '$2y$10$iBwdwRWyNNAtEsjDA.Z.pe2Vn.i2PlWt9kudgmeYbToazLZJjLU3G',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 6',
                'role' => 'admin-kader',
                'username' => 'kader06',
                'password' => '$2y$10$G.1GmNr/hJrttp.ZWT5rHOrMWzoCz/DjozRKRjXW6KQL2FZwj6dMS',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 7',
                'role' => 'admin-kader',
                'username' => 'kader07',
                'password' => '$2y$10$jjQtcdr1fk92XOgRifOmVexuBgoRiQsxz/HngrqFUSR9bJUVg2siO',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 8',
                'role' => 'admin-kader',
                'username' => 'kader08',
                'password' => '$2y$10$8drBk//hgfbQq055QW6Z7uIyIahqgRt67bDzAOkP6nZxi00maDdti',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 9',
                'role' => 'admin-kader',
                'username' => 'kader09',
                'password' => '$2y$10$iwFkbp8TJAin6HgX3j/coeX.PyDndTfHhV50boHympH0pEw.eFqVm',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 10',
                'role' => 'admin-kader',
                'username' => 'kader10',
                'password' => '$2y$10$/sSog4dO9w11KyzntoZ2deHsLp9CMsr/zhHUORVVD02fqHvqn2sN6',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 11',
                'role' => 'admin-kader',
                'username' => 'kader11',
                'password' => '$2y$10$ybYWczmWrzdsUTTDPBiMz.k.pbtTrY9BAA4iUGGjyEx0slRrQHZvO',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 12',
                'role' => 'admin-kader',
                'username' => 'kader12',
                'password' => '$2y$10$WqyCL.UaiJY8JFQbdwNeueVlVSlB/HtnCz9tqLPbwpevqKypOK9nG',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 13',
                'role' => 'admin-kader',
                'username' => 'kader13',
                'password' => '$2y$10$a48/zDZt5p8WdP/fxhRUP.IplOC2du8fiAolmSv6skQrC3HuwiY4m',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 14',
                'role' => 'admin-kader',
                'username' => 'kader14',
                'password' => '$2y$10$k9xYdFmPlq7nTDhTuoXzleNYa/ApMJItDPTon3LhkPtj8Xu.8tfsK',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 15',
                'role' => 'admin-kader',
                'username' => 'kader15',
                'password' => '$2y$10$RNJSTOqMiH0q9kT98iIL4OgT/pyQb/19tE1iveZDvqNotBwuGAdSu',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 16',
                'role' => 'admin-kader',
                'username' => 'kader16',
                'password' => '$2y$10$7quMwbiyGbIQ4xRlIKW7xOIpMWSs8Wkdt3QXTxHlww/pD3OVP6Y3S',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 17',
                'role' => 'admin-kader',
                'username' => 'kader17',
                'password' => '$2y$10$Ftqqj1n8FtWcipDiYtX1he1N1QudUbH2UC7CgrFs0kEuz8jiLfiji',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 18',
                'role' => 'admin-kader',
                'username' => 'kader18',
                'password' => '$2y$10$dTQ/6QvUAr.8slkkLxIIAOTx68okGxDpWqbbT36bER6WCO9YwBiJC',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 19',
                'role' => 'admin-kader',
                'username' => 'kader19',
                'password' => '$2y$10$J1YNe48Y.5yw7FRlvzlNVu9p2DRxS6y5n5pJ98986nUuHqJWJYeiq',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 20',
                'role' => 'admin-kader',
                'username' => 'kader20',
                'password' => '$2y$10$FvSUzNyBE7YSG3.0jKwZE.oLZH4vwmSV5vo9uvKwOpOjg0fI0r9KW',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 21',
                'role' => 'admin-kader',
                'username' => 'kader21',
                'password' => '$2y$10$pfDLOKIbQJdzFX17wDUIRO1f1sTkJ8A9tVTkHkXwDQBSh4YTEospi',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 22',
                'role' => 'admin-kader',
                'username' => 'kader22',
                'password' => '$2y$10$je2PlXbQ76GOsolCJvuNXO4oNKGbjcyPYYvgj/COpcLoYlhn06O9y',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 23',
                'role' => 'admin-kader',
                'username' => 'kader23',
                'password' => '$2y$10$i6yibOSgX9EOS786GbaONOORQ.mM19GJFKj84SYjw3DTbChMNs9JO',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 24',
                'role' => 'admin-kader',
                'username' => 'kader24',
                'password' => '$2y$10$xEE4U.71srpJvhJUkHn/u.60y1C28tuXzBop5qcHw.TdhxuMFesb6',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 25',
                'role' => 'admin-kader',
                'username' => 'kader25',
                'password' => '$2y$10$6UuE5.TA.R.U7tJUgzsjn.ITtUhHdHrzkYiwG7bJnkvWUusmRG6QK',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 26',
                'role' => 'admin-kader',
                'username' => 'kader26',
                'password' => '$2y$10$Pjz2yojQw/UxqTTblCPe2eBIouU.EKgMjq9rRdwXpgpSz/dMWRS06',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 27',
                'role' => 'admin-kader',
                'username' => 'kader27',
                'password' => '$2y$10$P4eGcScGEVQFiq1RhrRGMOewmJR0ZtF9W78B5zYjOVwVesXwIxYEu',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 28',
                'role' => 'admin-kader',
                'username' => 'kader28',
                'password' => '$2y$10$bIyUrJWB90h.gCuvQIdqveBFZlyLUIiEU1fTh41gjoxqdGYuQVsJi',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 29',
                'role' => 'admin-kader',
                'username' => 'kader29',
                'password' => '$2y$10$nYGQfW.Y2c19Oet6dlIIh.d5F/oDONiPQqHpeqtOQYMhoMnH5TyGi',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 30',
                'role' => 'admin-kader',
                'username' => 'kader30',
                'password' => '$2y$10$5zL9YQUtrN23LIv9T7cfGemPddRqlPLv7Fo60rXFIIbgMrEFQKLIS',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 31',
                'role' => 'admin-kader',
                'username' => 'kader31',
                'password' => '$2y$10$vJ68a9LOr8o7DrH7LrGYcO/3MvHoHjQ5YsTm6U.VkMeWadfjK8Md6',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 32',
                'role' => 'admin-kader',
                'username' => 'kader32',
                'password' => '$2y$10$dJfjR53mR/bQd0ekutgdR.yktgv1mEmgOGKQqwPp..kDWrRKT5cBe',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 33',
                'role' => 'admin-kader',
                'username' => 'kader33',
                'password' => '$2y$10$40IbbBSudvPcW99PnUfRY.S5bJqOiT8KNtOsoHN6P9VVIZ81MLBy6',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 34',
                'role' => 'admin-kader',
                'username' => 'kader34',
                'password' => '$2y$10$IbYyjlqwKdBZm0PkUi/ANugxlIRQcc8BtVSu2ENYmnR.0utkmePPq',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 35',
                'role' => 'admin-kader',
                'username' => 'kader35',
                'password' => '$2y$10$B3iGrWPpmiafhlvNI5lRTOBJeVHxrdX9Sn1f4jXZfhh2EjyWL9je2',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 36',
                'role' => 'admin-kader',
                'username' => 'kader36',
                'password' => '$2y$10$mI0eOtDPeE/DYVqULEZzMOqOXi57M/WyYY2ndbZQTUVgtuNPJTLCi',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 37',
                'role' => 'admin-kader',
                'username' => 'kader37',
                'password' => '$2y$10$sjf9psucN1zIjBJTwZu5MOFZYZZADy5i9nfLvucnAMaTJKwvuHhOa',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 38',
                'role' => 'admin-kader',
                'username' => 'kader38',
                'password' => '$2y$10$3LBT0FWRRQe1s166ja8pFeTLxSWg3qIEG72OBKGFChZzeO28tCuF.',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 39',
                'role' => 'admin-kader',
                'username' => 'kader39',
                'password' => '$2y$10$YYwocMTOBsckYDAck.IUP.6ZQgoCcNazPq45hWoLzSt4JJGoUvKZ2',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'user 40',
                'role' => 'admin-kader',
                'username' => 'kader40',
                'password' => '$2y$10$QxIHk.Vz11yDJ4ezXRd2re6uEacNwfJXDXghF8BfNc/5ZwOPFilXi',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '01',
                'rt' => '01',
            ],
            [
                'nama' => 'Kelurahan Karangmekar',
                'role' => 'admin-kelurahan',
                'username' => 'admin-kelurahan',
                'password' => '$2y$10$BZf3tec63zF9SjAzUeZRVeDhGmT0Fita1ht/a2dv1kfRvasQyarSG',
                'kecamatan' => 'Cimahi Tengah',
                'kelurahan' => 'Karangmekar',
                'rw' => '0003',
                'rt' => '0001',
            ],
            [
                'nama' => 'Demokec',
                'role' => 'admin-kecamatan',
                'username' => 'demokec',
                'password' => '$2y$10$VAILO/FdpZJVN8CFpYRYwudZv8xNni4q6k5nMU2yCGVTIh8l6g9fO',
                'kecamatan' => 'Cimahi Utara',
                'kelurahan' => 'Melong',
                'rw' => '0004',
                'rt' => '0004',
            ],
            [
                'nama' => 'test',
                'role' => 'admin-kader',
                'username' => 'test001',
                'password' => '$2y$10$f5FtkdO1Er6N3S136azl1ulNTXNHTnVWtBwKTvT.48R8fnUzcxSzK',
                'kecamatan' => 'CIMAHI SELATAN',
                'kelurahan' => 'CIBEBER',
                'rw' => '0001',
                'rt' => '0001',
            ],
            [
                'nama' => 'test',
                'role' => 'admin-kader',
                'username' => 'test002',
                'password' => '$2y$10$kgDCW6zEA4l/C4jvP.njruAfE9L.xm7gfe0P/YyZ1G3Z.26GVgHzq',
                'kecamatan' => 'CIMAHI TENGAH',
                'kelurahan' => 'KARANGMEKAR',
                'rw' => '0001',
                'rt' => '0001',
            ],
        ];

        // Simpan data ke dalam tabel user
        foreach ($users as $user) {
            User::create($user);
        }
    }
}
